# Generated by Django 2.1.4 on 2018-12-17 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mtm',
            new_name='Home',
        ),
        migrations.DeleteModel(
            name='Arabic',
        ),
    ]
