# Generated by Django 2.1.4 on 2018-12-17 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arabic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shaykh',
            old_name='description',
            new_name='biography',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='description',
            new_name='biography',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='description',
            new_name='biography',
        ),
    ]
